# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/funda/"
  bin = "./tmp/main"
  include = [
    ".go",
    "go.mod",
    "go.sum",
    ".air.toml",
    "cmd/",
    "pkg/",
    "internal/"
  ]
  exclude = []

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"
