database:
  type: "sqlite"
  name: "funda_database.db"

oauth:
  jwtSecret: "XpByJ91SbkhngTHC8UEwCY3zdL0uijsPyTUDM4+KaVdIM2+3g3fJe+TntQLFDloFUNnIj5GswFudJcDcQz36Hw=="

cors:
  allowOrigins:
    - "http://localhost:4100"
  allowMethods:
    - "GET"
    - "POST"
    - "DELETE"
    - "PUT"
  allowHeaders:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  allowCredentials: true
  exposeHeaders:
    - "Content-Length"
  maxAge: 3600

